language: android
jdk: oraclejdk8

# BugFix for 'git rev-list --full-history --all' showing too low commit count
git:
  depth: 10000

env:
  global:

    - SLAVE_AAPT_TIMEOUT=30
    - TERM=dumb
    - GRADLE_OPTS="-XX:MaxPermSize=2024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m  -Dfile.encoding=UTF-8"


matrix:
  fast_finish: true

android:
  components:

      - tools
      - build-tools-23.0.3
      - android-23
      - platform-tools
      - extra-android-support
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository

  licenses:

    - android-sdk-license-.+

before_install:

  # retrolambda
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME

  # updating submodules
  - git submodule update --init --recursive

  # executable gradle wrapper
  - chmod u+x gradlew

  # list installed android sdk
  - android list sdk --no-ui --all --extended

  # list installed android targets
  - android list targets

script:
  - ./gradlew tasks
  - ./gradlew -v
  - ./gradlew clean assemble  --stacktrace  --info -Dpre-dex=false

notifications:
  email: false