language: android
jdk: oraclejdk8

# BugFix for 'git rev-list --full-history --all' showing too low commit count
git:
  depth: 10000

env:
  global:

    - SLAVE_AAPT_TIMEOUT=30
    - TERM=dumb
    - GRADLE_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m  -Dfile.encoding=UTF-8"


matrix:
  fast_finish: true

android:
  components:

      - tools
      - build-tools-23.0.3
      - android-23
      - platform-tools
      - extra-android-support
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository

  licenses:

    - android-sdk-license-.+

# Emulator Management: Create, Start and Wait

before_script:

 # - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
 # - emulator -avd test -no-audio -no-window &
 # - android-wait-for-emulator
 # - adb shell input keyevent 82 &
 # - adb devices

before_install:

  # retrolambda
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME

  # updating submodules
  - git submodule update --init --recursive

  # executable gradle wrapper
  - chmod u+x gradlew

  # list installed android sdk
  - android list sdk --no-ui --all --extended

  # list installed android targets
  - android list targets

install: true

script:
  - ./gradlew tasks
  - ./gradlew -v
  - ./gradlew clean app:assemble applicationtest:assemble --stacktrace  --info -Dpre-dex=false
  - ./gradlew app:uploadReleaseBranchVersionToHockeyApp
  # - ./gradlew app:installQuesticoDebug app:installCircleDebug
  # - ./gradlew applicationtest:connectCheck

after_script: true
  # - adb logcat &

after_success:

after_failure: true

notifications:
  email: false
  #slack:
    #rooms:
    #  - 'exozet:'
    #on_success: always
    #on_failure: never
    #on_start: never
